#!/usr/bin/python
import os, sys, signal 
from time import sleep
from subprocess import Popen, PIPE
import abtserver.rpc_main

if __name__ == "__main__":
	
	try:
		if os.path.exists("/opt/abt") == False: # check for abt directory , if false then 
			try:
				print "creating directory"
				os.system("mkdir -p /opt/abt/db") # create abt directory and db to host all databases
				os.system("cp ./src/places.db /opt/abt/") # copy places.db from /src to abt
				
			except:
				print "can't create directory somthing is wrong"

		else:
		 	if os.path.exists("/opt/abt/db") == False: # check for abt/db directory , if false then
				try:
					print "creating directory"
					os.system("mkdir /opt/abt/db") # create db directory in abt
					os.system("cp ./src/places.db /opt/abt/") # copy places.db from /src to abt
				except:
					print "can't create directory somthing is wrong"
			else:
				print "db already exist"
				
			print "abt already exist"
		#calling rungnukhata() from rpc_main.py which is in gnukhataserver
		#getpid()	# ??
		abtserver.rpc_main.runabt()
		
	except:
		print "inside exception"
		'''
		var = "pgrep gkstart"
		# var = "ps -eo pid,args | grep '/python \./gkstart' | cut -f 2 -d ' '"
		val = Popen(var,shell=True,stdout=PIPE).stdout.read().strip('\n')
		pid = val.split("\n")
		print pid
		os.kill(int(pid[0]),signal.SIGKILL)
		print "sleeping for 2 sec"
		sleep(3)

		# run again
		os.getpid()
		gnukhataserver.rpc_main.rungnukhata()
		'''
