#!/usr/bin/python
import os, sys, signal 
from time import sleep
from subprocess import Popen, PIPE
import abtserver.rpc_main

if __name__ == "__main__":
	
	try:
		if os.path.exists("/opt/abt") == False: # check for abt directory , if false then 
			try:
				print "creating abt and db directory and copying places.db to abt"
				os.system("mkdir -p /opt/abt/db") # create abt directory and db to host all databases
				os.system("cp ./src/places.db /opt/abt/") # copy places.db from /src to abt
				
			except:
				print "can't create directory somthing is wrong"

		else:
		 	if os.path.exists("/opt/abt/db") == False: # check for abt/db directory , if false then
				try:
					print "creating db directory and copying places.db"
					os.system("mkdir /opt/abt/db") # create db directory in abt
					os.system("cp ./src/places.db /opt/abt/") # copy places.db from /src to abt
				except:
					print "can't create directory somthing is wrong"
			else:
				print "db already exist"
				
			print "abt already exist"
		os.system("sudo su -c '/usr/bin/postgres -D /var/data &' postgres")
		abtserver.rpc_main.runabt()
		
	except:
		print "inside exception"
		
